<!-- function for finding X value -->
<h2 class="page-header">Function for finding X value</h2>
<p><h4>3, 5, 9, 15, X  - Please create new function for finding X value</h4></p>
<p>X Value = <?= $Xvalue?></p>
<!-- function for finding Y value -->
<h2 class="page-header">Function for finding Y value</h2>
<p><h4>(Y + 24)+(10 × 2) = 99  - Please create new function for finding Y value</h4></p>
<p>Y Value = <?= $Yvalue?></p>
<!-- function for finding X value -->
<h2 class="page-header">Function for finding X value</h2>
<p><h4>If 1 = 5 , 2 = 25 , 3 = 325 , 4 = 4325 Then 5 = X - Please create new function for finding X value</h4></p>
<p>X Value = <?=$newXvalue?></p>